name: BUILD

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install deps
        run: npm ci --no-optional

      - name: Run lint
        run: npm run lint -- --no-fix

      - name: Run tests
        run: npm run test:unit

      - name: Build
        run: npm run build

      - name: Prepare Deploy
        if: github.ref == 'refs/heads/develop'
        run: |
          cp ./server/config.json ./dist/config.json
      
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
